### PR TITLE
File encoding fix for linux and python3 fixes

### PR DESCRIPTION
**Pull request by johndpope**
Some simple and dirty fixes to get script working on python3

### CODE REVIEW

**Comment by johndpope** [comment]
this doesn't seem to work on osx. 
iconv -o utf8_movie_lines.txt -f iso-8859-1 -t utf-8 movie_lines.txt

if I use 
iconv  utf8_movie_lines.txt -f iso-8859-1 -t utf-8 movie_lines.txt
- this breaks here. 
iconv: movie_lines.txt:5440:83: cannot convert
I see the problem here
L19462 +++$+++ u198 +++$+++ m13 +++$+++ ELAINE +++$+++ You got a telegram from head�quarters today.

 iconv -f iso-8859-1 -t **utf-8** movie_lines.txt >utf8_movie_lines.txt
 iconv -f iso-8859-1 -t **utf-8** movie_conversations.txt >utf8_movie_conversations.txt

**Comment by Mindii** [comment]
ok, just starting to look that again so most likely iso-8859-1 is not right encoding to use only thing that I found was that those original files are from 2010 and they were encoded with unknown-8bit codec

**Comment by yashkumar6640** [comment]
In your compat.py file just add one more argument where its returning bytes_or_text(encoding), instead make it bytes_or_text(encoding, "ignore"). This will work.
Find compat.py file under your tensorflow library.

**Comment by krati23** [comment]
Thanks yash..it works!!:)

**Pull request closed without merging**
